version: '3.8'
services:
  go-cve-dictionary:
    image: vuls/go-cve-dictionary
    volumes:
      - $PWD:/vuls
      - $PWD/go-cve-dictionary-log:/var/log/vuls
  goval-dictionary:
    image: vuls/goval-dictionary
    volumes:
      - $PWD:/goval-dictionary
      - $PWD/goval-dictionary-log:/var/log/goval-dictionary
  gost:
    image: vuls/gost
    volumes:
      - $PWD:/vuls
      - $PWD/gost-log:/var/log/gost
  go-exploitdb:
    image: vuls/go-exploitdb
    volumes:
      - $PWD:/vuls
      - $PWD/go-exploitdb-log:/var/log/go-exploitdb
  go-msfdb:
    image: vuls/go-msfdb
    volumes:
      - $PWD:/go-msfdb
      - $PWD/go-msfdb-log:/var/log/go-msfdb
  vuls:
    image: vuls/vuls
    volumes:
      - $PWD:/vuls
      - $PWD/vuls-log:/var/log/vuls
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.ssh:/root/.ssh:ro
